# Generated by Django 4.2.4 on 2023-08-15 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_city_remove_customer_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_calories', models.CharField(max_length=200)),
                ('preferred_protein', models.CharField(max_length=200)),
                ('preferred_carbohydrates', models.CharField(max_length=200)),
                ('preferred_fats', models.CharField(max_length=200)),
                ('preferred_vitamins', models.CharField(max_length=200)),
                ('preferred_minerals', models.CharField(max_length=200)),
                ('preferred_fiber', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
