# Generated by Django 4.2.4 on 2023-08-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lecturerpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_carbohydrates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_fats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_fiber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_minerals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_vitamins',
            field=models.IntegerField(),
        ),
    ]
