# Generated by Django 4.2.4 on 2023-08-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_lecturerpreference_preferred_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_fiber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_minerals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_protein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='preferred_vitamins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
