# Generated by Django 4.2.4 on 2023-08-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', help_text='Font awesome icon', max_length=20),
            preserve_default=False,
        ),
    ]
