# Generated by Django 4.2.4 on 2023-08-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_alt_text_remove_product_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.IntegerField(help_text='The amount of energy provided by the food.Example: 150 (kcal)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.IntegerField(help_text='The total amount of carbohydrates in the food, including sugars, fiber, and starches. Example: 20.3 (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.IntegerField(help_text='The total amount of fats in the food, including saturated fats and unsaturated fats. Example: 5.2 (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fiber',
            field=models.IntegerField(help_text='The amount of dietary fiber in the food. Example: 3.5 (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minerals',
            field=models.IntegerField(help_text='The amount of various minerals present in the food. Example: Iron: 2.3 mg, Calcium: 120 mg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.IntegerField(help_text='The amount of protein in the food. Example: 8.5 (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitamins',
            field=models.IntegerField(help_text='The amount of various vitamins present in the food. Example: Vitamin C: 10 mg, Vitamin A: 200 IU'),
        ),
    ]
